README.md, docs/usage.md, src/aiohappyeyeballs/__init__.py, src/aiohappyeyeballs/types.py, src/aiohappyeyeballs/utils.py, tests/test_utils.py
```python
aiohappyeyeballs.pop_addr_infos_interleave(addr_info, 1)
aiohappyeyeballs.remove_addr_infos(addr_info, "dead::beef::")
```
=> feat: add utils

README.md, docs/usage.md, src/aiohappyeyeballs/__init__.py, src/aiohappyeyeballs/utils.py, tests/test_utils.py
`create_connection` usually wants one local_addr, but we support multiple because internally cpython does as well so as long as they are in `addr_info` format so we need a util for easy conversions.
```python
local_addr_infos = addr_to_addr_infos(("127.0.0.1",0))
```
=> feat: add addr_to_addr_info util for converting addr to addr_infos

src/aiohappyeyeballs/utils.py, tests/test_utils.py
cpython does not require interleave to be set for creating connections
and will default it to 1 if happy_eyeballs_delay is set, so mirror
that behavior in the util
=> feat: make interleave with pop_addr_infos_interleave optional to match cpython

src/aiohappyeyeballs/impl.py
This is a small performance improvement. We already avoid happy eyeballs when there is only a single one, and we can avoid interleave as well
=> feat: avoid _interleave_addrinfos when there is only a single addr_info

.github/workflows/ci-cd.yml, src/aiohappyeyeballs/impl.py
Patch missing `asyncio.futures.TimeoutError` with Python < 3.8.2
Library will no longer fail on Python 3.8.0 and Python 3.8.1
fixes https://github.com/aio-libs/aiohttp/issues/8556
=> fix: workaround broken `asyncio.staggered` on python < 3.8.2

pyproject.toml
Update classifiers to include license for tooling that requires it.
No
fixes #59
=> fix: update classifiers to include license

.github/workflows/ci-cd.yml
This is the first release since the permissions were reworked. The release failed because the `build_release` pushes to `main` https://github.com/aio-libs/aiohappyeyeballs/actions/runs/10184595236
=> chore: fix permissions in release CI workflow

pyproject.toml
Add missing python version classifiers
none
=> fix: add missing python version classifiers

.github/workflows/ci-cd.yml
Fixes the failure to publish wheels and packages to github
=> chore: fix publishing package to github

src/aiohappyeyeballs/impl.py, tests/test_impl.py
remove redundant asyncio import
no
https://github.com/aio-libs/aiohappyeyeballs/pull/61#discussion_r1699031241
=> chore: remove redundant asyncio import

pyproject.toml
The intent is to license the code under the same terms as python itself as the code is derived from cpython
no
fixes #59 (again)
=> fix: adjust license classifier to better reflect license terms

src/aiohappyeyeballs/impl.py, tests/test_impl.py
Preserve errno if all exceptions have the same errno
solves a regression in aiohttp
fixes #76
=> fix: preserve errno if all exceptions have the same errno

pyproject.toml
The license is intended to be the same as cpython itself https://spdx.org/licenses/Python-2.0.1.html
Unfortunately as there currently is no exact matching classifier, remove the classifier: https://pypi.org/classifiers/
no
closes #79
closes #81
=> fix: adjust license to Python-2.0.1

pyproject.toml
Correct classifier for license Python-2.0.1 according to available classifiers listed at https://pypi.org/classifiers/
Without this patch, pip-licenses disrupted CI license check with below error which was not raised at version prior 2.3.5.
```license Other/Proprietary License not in allow-only licenses was found for package aiohappyeyeballs:2.3.6```
It seems that the change was made by [this commit](https://github.com/aio-libs/aiohappyeyeballs/commit/30a2dc57c49d1000ebdafa8c81ecf4f79e35c9f3), which correctly removed `CNRI Python License` part but unfortunately didn't update properly which is this PR for.
There is no change in functionalities except license checking above.
=> fix: correct classifier for license Python-2.0.1

README.md
Fix a trivial typo in `README.md` – `such was` in place of `such as`.
No.
N/A, no issue opened.
=> docs: fix a trivial typo in README.md

README.md
Update readme to include license information, as we seem to get a new issue from people using license scanners that are unaware of the python license each week
"aiohappyeyeballs is licensed under the same terms a cpython itself."
=> chore: update readme to include license information

src/aiohappyeyeballs/impl.py
remove loop param from call to `staggered.staggered_race`
ref https://github.com/aio-libs/aiohttp/issues/8599#issuecomment-2378018509
ref https://github.com/python/cpython/issues/124309
ref https://github.com/python/cpython/issues/124639
ref https://github.com/python/cpython/pull/124390
ref https://github.com/python/cpython/pull/124574
ref https://github.com/python/cpython/pull/124573
no
=> fix: avoid passing loop to staggered.staggered_race

src/aiohappyeyeballs/_staggered.py, src/aiohappyeyeballs/impl.py, src/aiohappyeyeballs/staggered.py, tests/test_impl.py
https://github.com/python/cpython/issues/124639#issuecomment-2378129834
=> fix: copy staggered from standard lib for python 3.12+

src/aiohappyeyeballs/impl.py, tests/test_impl.py
Its possible that uvloop raises RuntimeError during connect. ie `RuntimeError: File descriptor 59 is used by transport <TCPTransport closed=False reading=True 0x55a6ec5c9460>`.  Currently we don't trap `RuntimeError` as the code copied from `asyncio.base_events` assumed only `OSError` can happen.  Its possible that selector_events can raise `RuntimeError` as well https://github.com/python/cpython/blob/e44eebfc1eccdaaebc219accbfc705c9a9de068d/Lib/asyncio/selector_events.py#L271 but it doesn't seem to happen in practice as the root cause appears to be a bug in `uvloop`.  It may be that [`loop.sock_connect`](https://github.com/MagicStack/uvloop/blob/79d5dcdb0785d9319b8b04f99e7a733ed56e9b46/uvloop/loop.pyx#L2614) is not cancellation safe in `uvloop` and is leaking the socket fd allocation on …
=> fix: re-raise RuntimeError when uvloop raises RuntimeError during connect

src/aiohappyeyeballs/impl.py, tests/test_impl.py
It is possible for `loop.sock_connect` to fail in such a way that the wrapped socket no longer refers to a valid file descriptor. In this, the exception handler can fail on the attempt to call `sock.close()`. When this happens, `start_connection` can have `sock == None` and `exceptions == []`. This causes an `IndexError` because it assumes that `exceptions` always contains at least one exception instance.
I experienced crashes when handling connections with short timeouts.
=> fix: handle OSError on failure to close socket instead of raising IndexError

.github/workflows/ci-cd.yml, poetry.lock, pyproject.toml, src/aiohappyeyeballs/impl.py, tests/test_impl.py
Python 3.8 has reached EOL, and the CI runners now fail
Python 3.8 no longer supported
=> chore: drop Python 3.8 support

.github/workflows/ci-cd.yml
This was only pinned for Python 3.8
=> chore: update ubuntu CI runner to latest

.github/dependabot.yml
Add GHA to the dependabot config as it was missing for this repo
=> chore: update dependabot.yml to include GHA

pyproject.toml
Pull request #131 was incorrectly merged with #132. This causes `classifiers` to end up in `[tool.poetry]` again.
This is against what we want, since we don't want to do automatic classifiers enrichment. Behavior is documented in [Poetry docs](https://python-poetry.org/docs/pyproject/#classifiers)
Metadata with this patch looks like this
```
Metadata-Version: 2.3
Name: aiohappyeyeballs
Version: 2.4.4
Summary: Happy Eyeballs for asyncio
License: PSF-2.0
Author: J. Nick Koston
Author-email: nick@koston.org
Requires-Python: >=3.9
Classifier: Development Status :: 5 - Production/Stable
Classifier: Intended Audience :: Developers
Classifier: Natural Language :: English
Classifier: Operating System :: OS Independent
Classifier: Topic :: Software Development :: Libraries
Classifier: Programming …
```
=> fix: keep classifiers in project to avoid automatic enrichment

poetry.lock
- Updating certifi (2024.12.14 -> 2025.1.31)
- Updating nh3 (0.2.20 -> 0.2.21)
- Updating pytest (8.3.4 -> 8.3.5)
- Updating coverage (7.6.10 -> 7.6.12)
- Updating pytest-asyncio (0.25.2 -> 0.25.3)
dependabot is currently broken with poetry 2 so we need to do this manually to resolve  https://github.com/aio-libs/aiohappyeyeballs/security/dependabot/18
=> chore: manually update deps

src/aiohappyeyeballs/_staggered.py, tests/test_impl.py, tests/test_staggered.py
- Instead of raising SystemExit which causes a RuntimeError, mock out SystemExit to a new exception
- Make sure the event loop is closed in tests
no
fixes #97
=> fix: resolve warnings when running tests

src/aiohappyeyeballs/impl.py, tests/test_impl.py
The first attempt to fix this was to use the cpython staggered race updates in #142 but there is still a race there where there can be multiple winners. Instead we now accept that we will not be able to cancel all coros in time and there will always be a risk of multiple winners. We store all sockets in a set that were not already cleaned up and we close all but the first winnner after the staggered race finishes.
bug fix
related aiohttp issue https://github.com/aio-libs/aiohttp/issues/10506
=> fix: close runner up sockets in the event there are multiple winners

docs/api_reference.rst, docs/conf.py, docs/index.md
Creates an api_reference.rst file to expose the existing documentation for the few functions that have docstrings, as well as add documentation for AddrInfoType and SocketFactoryType. Now, these can be properly pointed to by other projects' documentation.
Publish documentation so it can be pointed to by other projects.
No.
N/A
=> feat(docs): publish documentation

.github/workflows/ci-cd.yml
Removes an exclude line in the CI for Python 3.8.0
This should have been removed when we dropped Python 3.8 support
=> chore: remove unused CI exclude for Python 3.8.0

.github/workflows/ci-cd.yml, src/aiohappyeyeballs/_staggered.py, src/aiohappyeyeballs/types.py, tests/test_staggered.py, tests/test_types.py
https://github.com/aio-libs/aiohappyeyeballs/issues/150 shows we have a problem with Python < 3.9.2
This is because of a bug in cpython that was not fixed until 3.9.2 https://github.com/python/cpython/issues/87131
fixes #150
=> fix: resolve TypeError on import for Python < 3.9.2

.github/workflows/ci-cd.yml
3.9.1 images are no longer available.
I don't think we will regress #150 before 2025-10 so this is low risk to drop
=> chore: drop Python 3.9.1 CI runner
